//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.FluentValidation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X.FluentValidation.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not allowed. allowed types is {ContentTypes}..
        /// </summary>
        internal static string FileContentTypeValidator {
            get {
                return ResourceManager.GetString("FileContentTypeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of &apos;{PropertyName}&apos; must be less than {MaxLength} MB. You uploaded {TotalLength} MB..
        /// </summary>
        internal static string FileMaximumLengthValidator {
            get {
                return ResourceManager.GetString("FileMaximumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of &apos;{PropertyName}&apos; must be at least {MinLength} MB. You uploaded {TotalLength} MB..
        /// </summary>
        internal static string FileMinimumLengthValidator {
            get {
                return ResourceManager.GetString("FileMinimumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type is not allowed..
        /// </summary>
        internal static string FileSignatureValidator {
            get {
                return ResourceManager.GetString("FileSignatureValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type is not allowed. Allowed types is {Types}..
        /// </summary>
        internal static string FileTypeValidator {
            get {
                return ResourceManager.GetString("FileTypeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must contain fewer than {MaxElements} items. The {PropertyName} contains {TotalElements} element..
        /// </summary>
        internal static string MaximumElementsValidator {
            get {
                return ResourceManager.GetString("MaximumElementsValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must contain at least {MinElements} items. The {PropertyName} contains {TotalElements} element..
        /// </summary>
        internal static string MinimumElementsValidator {
            get {
                return ResourceManager.GetString("MinimumElementsValidator", resourceCulture);
            }
        }
    }
}
